\input texinfo   @c -*-texinfo-*-

@c ./gendocs.sh --email cepek@gnu.org sqltutor "GNU Sqltutor - Web Based Interactive Tutorial of SQL"

@c %**start of header
@setfilename sqltutor.info
@c documentencoding UTF-8
@include version.texi
@settitle Sqltutor @value{VERSION}
@setchapternewpage odd

@finalout
@c %**end of header

@copying
This manual (@value{UPDATED}) is for Sqltutor (version
@value{VERSION}).

Copyright @copyright{} 2008 Ales Cepek

@quotation
Permission is granted to copy, distribute and/or modify this document
under the terms of the @acronym{GNU} Free Documentation License,
Version 1.2 or any later version published by the Free Software
Foundation; with no Invariant Sections, with the Front-Cover texts
being ``A @acronym{GNU} Manual,'' and with the Back-Cover Texts as in
(a) below.  A copy of the license is included in the section entitled
``@acronym{GNU} Free Documentation License.''

(a) The FSF's Back-Cover Text is: ``You have the freedom to copy and
modify this @acronym{GNU} manual.  Buying copies from the @acronym{FSF}
supports it in developing @acronym{GNU} and promoting software
freedom.''
@end quotation
@end copying

@c .... dircategory

@titlepage
@title Sqltutor
@subtitle SQL interactive tutorial
@subtitle @value{UPDATED}, Sqltutor Version @value{VERSION}

@author by Ales Cepek

@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@c Output the table of the contents at the beginning.
@contents

@ifnottex
@node Top
@top Sqltutor
@c @insertcopying
@end ifnottex

@menu
* Introduction::
* Concepts::
* How to install Sqltutor::
* Internals::

* Copying::
* Copying This Manual::

* Index::
@end menu

@node Introduction
@unnumbered Introduction
@cindex introduction
@include intro.texi

@node Concepts
@chapter The Concepts of Sqltutor
@include concepts.texi

@node How to install Sqltutor
@chapter How to install Sqltutor
@cindex how to install
@include install.texi

@node Internals
@chapter Internals
@cindex internals
@include internals.texi

@node Copying
@unnumbered GNU GENERAL PUBLIC LICENSE
@include gpl-3.0.texi

@node Copying This Manual
@appendix Copying This Manual
@include fdl.texi

@node Index
@unnumbered Index

@printindex cp

@bye
