\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename sqltutor.info
@c documentencoding UTF-8
@include version.texi
@settitle SQLtutor @value{VERSION}
@setchapternewpage odd

@finalout
@c %**end of header

@c @copying
@c This manual (@value{UPDATED}) is for SQLtutor (version
@c @value{VERSION}).
@c 
@c Copyright @copyright{} 2008 Ales Cepek
@c 
@c @quotation
@c Permission is granted to copy, distribute and/or modify this document
@c under the terms of the @acronym{GNU} Free Documentation License,
@c Version 1.2 or any later version published by the Free Software
@c Foundation; with no Invariant Sections, with the Front-Cover texts
@c being ``A @acronym{GNU} Manual,'' and with the Back-Cover Texts as in
@c (a) below.  A copy of the license is included in the section entitled
@c ``@acronym{GNU} Free Documentation License.''
@c 
@c (a) The FSF's Back-Cover Text is: ``You have the freedom to copy and
@c modify this @acronym{GNU} manual.  Buying copies from the @acronym{FSF}
@c supports it in developing @acronym{GNU} and promoting software
@c freedom.''
@c @end quotation
@c @end copying

@c .... dircategory

@titlepage
@title SQLtutor
@subtitle SQL interactive tutorial
@subtitle @value{UPDATED}, SQLtutor Version @value{VERSION}

@author by Ales Cepek

@page
@vskip 0pt plus 1filll
@c insertcopying
@end titlepage

@c Output the table of the contents at the beginning.
@contents

@ifnottex
@node Top
@top SQLtutor
@c @insertcopying
@end ifnottex

@menu
* Introduction::
* Concepts::
* How to install SQLtutor::
* Internals::

* Copying::
* Copying This Manual::

* Index::
@end menu

@node Introduction
@unnumbered Introduction
@cindex introduction
@include intro.texi

@node Concepts
@chapter The Concepts of SQLtutor
@include concepts.texi

@node How to install SQLtutor
@chapter How to install SQLtutor
@cindex how to install
@include install.texi

@node Internals
@chapter Internals
@cindex internals
@include internals.texi

@node Copying
@unnumbered GNU GENERAL PUBLIC LICENSE
@include gpl-3.0.texi

@node Copying This Manual
@appendix Copying This Manual
@include fdl.texi

@node Index
@unnumbered Index

@printindex cp

@bye
