DROP TABLE t1 CASCADE;
CREATE TABLE t1 (
   num  INTEGER,
   name VARCHAR(1)
);

DROP TABLE t2 CASCADE;
CREATE TABLE t2 (
   num   INTEGER,
   value VARCHAR(3)
);

INSERT INTO t1 VALUES (1, 'a');
INSERT INTO t1 VALUES (2, 'b');
INSERT INTO t1 VALUES (3, 'c');

INSERT INTO t2 VALUES (1, 'xxx');
INSERT INTO t2 VALUES (3, 'yyy');
INSERT INTO t2 VALUES (5, 'zzz');
